<?php

/*
 * ************** CAUTION **************
 *
 * DO NOT EDIT THIS FILE as it will be overridden by Composer as part of
 * the installation/update process. The original file resides in the
 * SensioDistributionBundle.
 *
 * ************** CAUTION **************
 */

if (!isset($_SERVER['HTTP_HOST'])) {
    exit('This script cannot be run from the CLI. Run it from a browser.');
}

require_once dirname(__FILE__).'/../app/KunstmaanRequirements.php';

$requirements = new KunstmaanRequirements(isset($_GET['ehost']) ? $_GET['ehost'] : null, isset($_GET['eport']) ? $_GET['eport'] : null);

$majorProblems = $requirements->getFailedRequirements();
$minorProblems = $requirements->getFailedRecommendations();

$whiches = $requirements->getAllWhiches();

?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="robots" content="noindex,nofollow" />
        <title>Kunstmaan Configuration Checker</title>
        <link rel="stylesheet" href="bundles/framework/css/structure.css" media="all" />
        <link rel="stylesheet" href="bundles/framework/css/body.css" media="all" />
        <style type="text/css">
            /* styles copied from bundles/sensiodistribution/webconfigurator/css/install.css */
            body {
                font-size: 14px;
                font-family: "Lucida Sans Unicode", "Lucida Grande", Verdana, Arial, Helvetica, sans-serif;
            }
            .sf-reset h1.title {
                font-size: 45px;
                padding-bottom: 30px;
            }
            .sf-reset h2 {
                font-weight: bold;
                color: #FFFFFF;
                /* Font is reset to sans-serif (like body) */
                font-family: "Lucida Sans Unicode", "Lucida Grande", Verdana, Arial, Helvetica, sans-serif;
                margin-bottom: 10px;
                background-color: #aacd4e;
                padding: 2px 4px;
                display: inline-block;
                text-transform: uppercase;
            }
            .sf-reset ul a,
            .sf-reset ul a:hover {
                background: url(../images/blue-arrow.png) no-repeat right 6px;
                padding-right: 10px;
            }
            .sf-reset ul, ol {
                padding-left: 20px;
            }
            .sf-reset li {
                padding-bottom: 18px;
            }
            .sf-reset ol li {
                list-style-type: decimal;
            }
            .sf-reset ul li {
                list-style-type: none;
            }
            .sf-reset .symfony-blocks-install {
                overflow: hidden;
            }
            .sf-reset .symfony-install-continue {
                font-size: 0.95em;
                padding-left: 0;
            }
            .sf-reset .symfony-install-continue li {
                padding-bottom: 10px;
            }
            .sf-reset .ok {
                color: #fff;
                font-family: "Lucida Sans Unicode", "Lucida Grande", Verdana, Arial, Helvetica, sans-serif;
                background-color: #6d6;
                padding: 10px;
                margin-bottom: 20px;
            }
            .sf-reset .ko {
                background-color: #d66;
            }
            .version {
                text-align: right;
                font-size: 10px;
                margin-right: 20px;
                background-color:black;
                padding:10px;
            }
            .sf-reset a,
            .sf-reset li a {
                color: #08C;
                text-decoration: none;
            }
            .sf-reset a:hover,
            .sf-reset li a:hover {
                color: #08C;
                text-decoration: underline;
            }
            .sf-reset textarea {
                padding: 7px;
            }

            ul.command-paths li {
                line-height:18px;
                padding-bottom:2px;
            }
        </style>
    </head>
    <body>
        <div id="content">
            <div class="header clear-fix">
                <div class="header-logo">
                    <img src="/images/kunstmaan-logo.png" alt="Kunstmaan" style="float:left"/>
                </div>

            </div>

            <div class="sf-reset">
                <div class="block">
                    <div class="symfony-block-content">
                        <h1 class="title">Szerver konfiguráció ellenőrzése<br /> a Kunstmaan telepítéséhez</h1>
                        <p>
                            A szkript ellenőrzi, hogy minden szerverbeállítás megfelelő-e a Kunstmaan telepítéséhez.
                        </p>

                        <?php if (count($majorProblems)): ?>
                            <h2 class="ko">Hibák</h2>
                            <p>Az alábbi hibákat mindenképpen javítani szükséges:</p>
                            <ol>
                                <?php foreach ($majorProblems as $problem): ?>
                                    <li><?php echo $problem->getHelpHtml() ?></li>
                                <?php endforeach; ?>
                            </ol>
                        <?php endif; ?>

                        <?php if (count($minorProblems)): ?>
                            <h2>Ajánlott javítások</h2>
                            <p>
                                Ajánlott javítások az optimális működéshez:
                            </p>
                            <ol>
                                <?php foreach ($minorProblems as $problem): ?>
                                    <li><?php echo $problem->getHelpHtml() ?></li>
                                <?php endforeach; ?>
                            </ol>
                        <?php endif; ?>

                        <?php if ($requirements->hasPhpIniConfigIssue()): ?>
                            <p id="phpini">*
                                <?php if ($requirements->getPhpIniConfigPath()): ?>
                                    A <strong>php.ini</strong> fájl helye: "<strong><?php echo $requirements->getPhpIniConfigPath() ?></strong>".
                                <?php else: ?>
                                    Hozzon létre egy "<strong>php.ini</strong>" fájlt.
                                <?php endif; ?>
                            </p>
                        <?php endif; ?>

                        <?php if (!count($majorProblems) && !count($minorProblems)): ?>
                            <p class="ok">Minden beállítás rendben a Kunstmaan telepíthető</p>
                        <?php endif; ?>

                        <ul class="symfony-install-continue">
                            <?php if (count($majorProblems) || count($minorProblems)): ?>
                                <li><a href="km-check.php">Újraellenőrzés</a></li>
                            <?php endif; ?>
                        </ul>

                        <h2>Elasticsearch</h2>
                        
                        <p>Elasticsearch URL: http://<?php echo $requirements->getElasticHost(); ?>:<?php echo $requirements->getElasticPort(); ?></p>
                        <?php $result = $requirements->checkElastic(); ?>
                        <?php if ($result === false) : ?>
                            <p><span style="color:red">Az Elasticsearch info nem kérdezhető le! Adja meg a host és port értékeket a lenti űrlapon az újraellenőrzéshez!</span></p>
                        <?php else : ?>
                            <p>Elasticsearch verzió: <strong><?php echo $result['version']['number']; ?></strong></p>
                        <?php endif; ?>
                        <form action="" method="get">
                            <label>ElasticSearch host: </label>
                            <input type="text" name="ehost" value="<?php echo isset($_GET['ehost']) ? $_GET['ehost'] : '';?>" />
                            <label>ElasticSearch port: </label>
                            <input type="text" name="eport" value="<?php echo isset($_GET['eport']) ? $_GET['eport'] : '';?>" />
                            <input type="submit" value="Ellenőrzés" />
                        </form>
                        <h2>Parancsok elérhetősége</h2>
                        <ul class="command-paths">
                            <?php foreach ($whiches as $file => $path) : ?>
                                <li><?php echo $file; ?>: <strong><?php echo $path; ?></strong></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="version"><img src="/images/webtown.png" /></div>
        </div>
    </body>
</html>
